### ISSUE TITLE
Setting a zls path via Atom's GUI does not work

### ISSUE THREAD

**Issue by ashpool37** [pfgithub/language-zig-zls#1]
### Steps to reproduce:

1. In Atom go to Edit -> Preferences -> Packages -> language-zig-zls -> Settings
1. Enter a path to `zls` into the "zls path" field

### Expected behavior

1. The package recognizes and uses the specified `zls` binary
1. The warning about setting a `zls` path is gone

### Actual behavior

1. The value is saved under the key `language-zig-zls.zls` in `config.cson`
1. The package seems to ignore the value
1. The warning about setting a `zls` path persists

### Workaround

Manually specify the value in `config.cson`:
```
  "language-zig":
    zls: "/path/to/zls"
```

**Comment by pfgithub** [comment]
I was developing with the package name language-zig and forgot to edit it once I found out language-zig was taken already, oops.
